version: "3.9"
services:
  challenge-meli: 
    container_name: challenge-meli
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data_base:/app/data_base